# Generated by Django 3.1.7 on 2021-04-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('User_Name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('Confirm_password', models.CharField(max_length=20)),
            ],
        ),
    ]
