# Generated by Django 3.1.7 on 2021-04-16 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_confirm_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
    ]
